[project]
name = "walls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "textual>=7.2.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.1",
    "pillow>=10.2.0",
    "textual-image>=0.8.0",
]
